source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'CardPackage' do

#QR and barcode scan library.
pod 'ZBarSDK'

#Harness the power of Auto Layout NSLayoutConstraints with a simplified, chainable and expressive syntax.
pod 'Masonry'

end
